package com.briozing.automation.utils;

public enum TestSteps {
    STEP_GET_ALL_POST,
    STEP_GET_POST_BY_ID,
    STEP_GET_ALL_COMMENTS,
    STEP_GET_ALL_ALBUMS,
    STEP_GET_ALL_PHOTOS,
    STEP_GET_ALL_TODOS,
    STEP_GET_ALL_USERS,
    STEP_GET_COMMENTS_BY_POST_ID,
    STEP_GET_POST_BY_USERID,
    STEP_CREATE_POST,
    STEP_UPDATE_POST,
    STEP_UPDATE_TITLE,
    STEP_DELETE_POST
}
